### ISSUE TITLE
need help for korean

### ISSUE THREAD

**Issue by skyer9** [sarbian/KerbalFontProject#1]
i want to know how to create notoshiftjis.font file.
i want to patch korean language for ksp.

**Comment by skyer9** [comment]
after severe googling, i created korean font assetbundle.
thank you.
![default](https://cloud.githubusercontent.com/assets/5269981/22626080/ab9c178e-ebe8-11e6-93e4-d923849149a5.png)

**Comment by quachhoangtam** [comment]
I'm also trying to put my language into the game, but I don't know how to create a .font file. Can you help me?
